const latte = {
  rosewater: "#d8dee9", // SnowStorm0
  flamingo: "#d08770",  // AuroraOrange
  pink: "#b48ead",      // AuroraPurple
  mauve: "#5e81ac",     // Frost3
  red: "#bf616a",       // AuroraRed
  maroon: "#bf616a",    // AuroraRed
  peach: "#d08770",     // AuroraOrange
  yellow: "#ebcb8b",    // AuroraYellow
  green: "#a3be8c",     // AuroraGreen
  teal: "#8fbcbb",      // Frost0
  sky: "#88c0d0",       // Frost1
  sapphire: "#81a1c1",  // Frost2
  blue: "#5e81ac",      // Frost3
  lavender: "#b48ead",  // AuroraPurple
  text: "#2e3440",      // PolarNight0
  subtext1: "#3b4252",  // PolarNight1
  subtext0: "#434c5e",  // PolarNight2
  overlay2: "#4c566a",  // PolarNight3
  overlay1: "#d8dee9",  // SnowStorm0
  overlay0: "#e5e9f0",  // SnowStorm1
  surface2: "#eceff4",  // SnowStorm2
  surface1: "#eceff4",  // SnowStorm2
  surface0: "#eceff4",  // SnowStorm2
  base: "#d8dee9",      // SnowStorm0
  mantle: "#e5e9f0",    // SnowStorm1
  crust: "#eceff4",     // SnowStorm2
};

const frappe = {
  rosewater: "#d8dee9", // SnowStorm0
  flamingo: "#d08770",  // AuroraOrange
  pink: "#b48ead",      // AuroraPurple
  mauve: "#5e81ac",     // Frost3
  red: "#bf616a",       // AuroraRed
  maroon: "#bf616a",    // AuroraRed
  peach: "#d08770",     // AuroraOrange
  yellow: "#ebcb8b",    // AuroraYellow
  green: "#a3be8c",     // AuroraGreen
  teal: "#8fbcbb",      // Frost0
  sky: "#88c0d0",       // Frost1
  sapphire: "#81a1c1",  // Frost2
  blue: "#5e81ac",      // Frost3
  lavender: "#b48ead",  // AuroraPurple
  text: "#2e3440",      // PolarNight0
  subtext1: "#3b4252",  // PolarNight1
  subtext0: "#434c5e",  // PolarNight2
  overlay2: "#4c566a",  // PolarNight3
  overlay1: "#d8dee9",  // SnowStorm0
  overlay0: "#e5e9f0",  // SnowStorm1
  surface2: "#eceff4",  // SnowStorm2
  surface1: "#eceff4",  // SnowStorm2
  surface0: "#eceff4",  // SnowStorm2
  base: "#d8dee9",      // SnowStorm0
  mantle: "#e5e9f0",    // SnowStorm1
  crust: "#eceff4",     // SnowStorm2
};

const macchiato = {
  rosewater: "#d8dee9", // SnowStorm0
  flamingo: "#d08770",  // AuroraOrange
  pink: "#b48ead",      // AuroraPurple
  mauve: "#5e81ac",     // Frost3
  red: "#bf616a",       // AuroraRed
  maroon: "#bf616a",    // AuroraRed
  peach: "#d08770",     // AuroraOrange
  yellow: "#ebcb8b",    // AuroraYellow
  green: "#a3be8c",     // AuroraGreen
  teal: "#8fbcbb",      // Frost0
  sky: "#88c0d0",       // Frost1
  sapphire: "#81a1c1",  // Frost2
  blue: "#5e81ac",      // Frost3
  lavender: "#b48ead",  // AuroraPurple
  text: "#2e3440",      // PolarNight0
  subtext1: "#3b4252",  // PolarNight1
  subtext0: "#434c5e",  // PolarNight2
  overlay2: "#4c566a",  // PolarNight3
  overlay1: "#d8dee9",  // SnowStorm0
  overlay0: "#e5e9f0",  // SnowStorm1
  surface2: "#eceff4",  // SnowStorm2
  surface1: "#eceff4",  // SnowStorm2
  surface0: "#eceff4",  // SnowStorm2
  base: "#d8dee9",      // SnowStorm0
  mantle: "#e5e9f0",    // SnowStorm1
  crust: "#eceff4",     // SnowStorm2
};

const mocha = {
  rosewater: "#d8dee9", // SnowStorm0
  flamingo: "#d08770",  // AuroraOrange
  pink: "#b48ead",      // AuroraPurple
  mauve: "#5e81ac",     // Frost3
  red: "#bf616a",       // AuroraRed
  maroon: "#bf616a",    // AuroraRed
  peach: "#d08770",     // AuroraOrange
  yellow: "#ebcb8b",    // AuroraYellow
  green: "#a3be8c",     // AuroraGreen
  teal: "#8fbcbb",      // Frost0
  sky: "#88c0d0",       // Frost1
  sapphire: "#81a1c1",  // Frost2
  blue: "#5e81ac",      // Frost3
  lavender: "#b48ead",  // AuroraPurple
  text: "#2e3440",      // PolarNight0
  subtext1: "#3b4252",  // PolarNight1
  subtext0: "#434c5e",  // PolarNight2
  overlay2: "#4c566a",  // PolarNight3
  overlay1: "#d8dee9",  // SnowStorm0
  overlay0: "#e5e9f0",  // SnowStorm1
  surface2: "#eceff4",  // SnowStorm2
  surface1: "#eceff4",  // SnowStorm2
  surface0: "#eceff4",  // SnowStorm2
  base: "#d8dee9",      // SnowStorm0
  mantle: "#e5e9f0",    // SnowStorm1
  crust: "#eceff4",     // SnowStorm2
};
